name: RefApp 3.x Appointments
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  repository_dispatch:
    types: [ qa ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout qaframework
        uses: actions/checkout@main
        with:
          repository: ${{github.repository}}
      - name: Run db and web containers
        run: docker-compose -f docker/docker-compose-refqa-3x.yml up -d
      - name: Wait for Openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/openmrs/login.htm)" != "200" ]]; do sleep 10; done
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Installing dependencies
        run: yarn install
      - name: Run appointments workflow tests
        run: cd packages/cypress && yarn refapp3Appointments
      - name: Upload screen recordings of failed tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: Screen recordings of failed tests
          path: packages/cypress/cypress/videos
